
import PptxGenJS from 'pptxgenjs';
import path from 'path';

const createMasterTemplate = async () => {
    const pres = new PptxGenJS();
    pres.layout = 'LAYOUT_16x9';

    // 1. Define Theme Colors (Navy, White, Gold)

    // 2. Define Master Slide "COVER_SLIDE"
    pres.defineSlideMaster({
        title: 'COVER_SLIDE',
        background: { color: 'FFFFFF' },
        objects: [
            // Dark Overlay Box (Navy Blue, 70% opacity approx)
            // Note: transparency is 0-100 in pptxgenjs (100 is fully transparent?)
            // { rect: { x: 0, y: 0, w: '100%', h: '100%', fill: { color: '1E3A8A', transparency: 20 } } },
            // Let's create the box on the slide itself or assume the image injection handles the background, 
            // and this box is an overlay. 
            { rect: { x: 0, y: 0, w: '100%', h: '100%', fill: { color: '1E3A8A', transparency: 20 } } },

            // Gold Accent Bar
            { rect: { x: 0, y: 5.5, w: '100%', h: 0.15, fill: { color: 'E2A300' } } },

            // Placeholders
            {
                placeholder: {
                    options: { name: 'title', type: 'title', x: 0.5, y: 2.5, w: 10, h: 1.5, align: 'left', fontFace: 'Calibri', fontSize: 44, color: 'FFFFFF', bold: true }
                },
                text: "PRESENTATION TITLE"
            },
            {
                placeholder: {
                    options: { name: 'subtitle', type: 'body', x: 0.5, y: 4.2, w: 10, h: 1, align: 'left', fontFace: 'Calibri', fontSize: 24, color: 'E2A300' }
                },
                text: "Subtitle Here"
            }
        ]
    });

    // 3. Define Master Slide "CONTENT_SLIDE"
    pres.defineSlideMaster({
        title: 'CONTENT_SLIDE',
        background: { color: 'FFFFFF' },
        objects: [
            // Header Bar (Navy)
            { rect: { x: 0, y: 0, w: '100%', h: 1.2, fill: { color: '1E3A8A' } } },
            // Gold Line
            { rect: { x: 0, y: 1.2, w: '100%', h: 0.05, fill: { color: 'E2A300' } } },
            // Slide Title Placeholder
            {
                placeholder: {
                    options: { name: 'header', type: 'title', x: 0.5, y: 0.2, w: 12, h: 0.8, align: 'left', fontFace: 'Calibri', fontSize: 28, color: 'FFFFFF', bold: true }
                },
                text: "Slide Title"
            },
            // Footer
            { text: { text: "Generated by Smart Presentation Machine", options: { x: 0.5, y: 7.2, w: 12, h: 0.3, align: 'center', fontFace: 'Calibri', fontSize: 10, color: '666666' } } }
        ]
    });

    // 4. Create Cover Slide (Slide 1)
    const cover = pres.addSlide({ masterName: 'COVER_SLIDE' });
    cover.addText("{{Title}}", { placeholder: 'title' });
    cover.addText("{{Subtitle}}", { placeholder: 'subtitle' });

    // 5. Create Dummy Content Slide (Slide 2) - To preserve the master and give us a clone Source
    const content = pres.addSlide({ masterName: 'CONTENT_SLIDE' });
    content.addText("{{SlideTitle}}", { placeholder: 'header' });
    // Add a text box we can target for Body
    content.addText("{{SlideBody}}", {
        shape: pres.ShapeType.rect, // Invisible shape to hold text? Or just text.
        x: 0.5, y: 1.5, w: 12, h: 5.0,
        fontFace: 'Calibri', fontSize: 16, color: '000000', align: 'left', valign: 'top',
        objectName: 'bodyText'
    });

    // Save
    const outputPath = path.join(process.cwd(), 'templates/business-analysis/template.pptx');
    await pres.writeFile({ fileName: outputPath });
    console.log(`Master Template created at: ${outputPath}`);
};

createMasterTemplate();
